baseurl = "/"
languageCode = "en-us"
# The title is better to be short
title = "Stacey | 汪"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
# Added three lines here:
hasCJKLanguage= true
enableEmoji= true
rssLimit= 100


[permalinks]
    post = "/post/:year/:month/:slug/"
    note = "/note/:year/:month/:slug/"

[[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "订阅"
    url = "/index.xml"

[params]
    description = "如何用文字描述清楚问题是相当重要的"
    footer = "&copy; [Stacey](https://stacey.netlify.app) 2020 | [Github](https://github.com/staceymoon)"
    customJS = [
    "js/fix-toc.js",
    "js/center-img.js",
    "js/right-quote.js",
    "js/no-highlight.js",
    "js/fix-footnote.js",
    "js/math-code.js",
    "js/external-link.js",
    "js/alt-title.js",
    "js/header-link.js"
    ]
    githubContentURL = "https://github.com/seamoonw/stacey_site/edit/master/content/"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"
